---
nginx_dir: "{{ project_source }}"
sites:
- name: "{{ domain }}"
  server_name: "www.{{ domain }} {{ domain }}"
  port: 80
  locations:
    - name: /
      pairs:
        proxy_pass: http://localhost:{{ port }}
        proxy_http_version: 1.1
        proxy_set_header: Upgrade $http_upgrade
        proxy_set_header: Connection 'upgrade'
        proxy_set_header: Host $host
        proxy_cache_bypass: $http_upgrade
